import {
  ClearanceStage,
  Requirement,
  StudentRecord,
  StaffRecord,
  SubmissionRecord,
  NotificationRecord,
  AuditLogRecord,
  SystemSettings,
  ClearanceStageKey,
} from '../types';

export const INITIAL_STAGES: ClearanceStage[] = [
  {
    id: 'admission',
    name: 'Admission Verification',
    order: 1,
    active: true,
    description: 'Verification of JAMB Admission Letter, institutional admission letter, and credentials.',
    color: '#3B82F6',
  },
  {
    id: 'faculty',
    name: 'Faculty / Departmental Sign-off',
    order: 2,
    active: true,
    description: 'Departmental dues confirmation and academic course registration verification.',
    color: '#EC4899',
  },
  {
    id: 'bursary',
    name: 'Bursary & Finance Clearance',
    order: 3,
    active: true,
    description: 'Audit of school fees Remita RRR receipts, late payment clearance, and financial verification.',
    color: '#F59E0B',
  },
  {
    id: 'library',
    name: 'Polytechnic Library Clearance',
    order: 4,
    active: true,
    description: 'Library card validation and return of all borrowed books and electronic resources.',
    color: '#8B5CF6',
  },
  {
    id: 'sports',
    name: 'Sports & Recreation Unit',
    order: 5,
    active: true,
    description: 'Sports equipment return and athletics department dues clearance receipt.',
    color: '#10B981',
  },
  {
    id: 'student_affairs',
    name: 'Directorate of Student Affairs',
    order: 6,
    active: true,
    description: 'Certificate of good conduct, student affidavit, and security clearance.',
    color: '#06B6D4',
  },
  {
    id: 'accommodation',
    name: 'Hall of Residence / Accommodation',
    order: 7,
    active: true,
    description: 'Hostel residency validation, room damage assessment, and key handover note.',
    color: '#6366F1',
  },
  {
    id: 'graduation',
    name: 'Academic Board / Final Graduation',
    order: 8,
    active: true,
    description: 'Final project clearance, convocation fee receipt, and alumni association registration.',
    color: '#14B8A6',
  },
];

export const INITIAL_REQUIREMENTS: Requirement[] = [
  // Admission
  {
    id: 'req_adm_01',
    stageId: 'admission',
    name: 'JAMB Admission Letter',
    description: 'Official JAMB admission letter showing institutional verification.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'req_adm_02',
    stageId: 'admission',
    name: 'O-Level Certificate / Statement of Results',
    description: 'Original WAEC/NECO/NABTEB certificate or official statement of result.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Library
  {
    id: 'req_lib_01',
    stageId: 'library',
    name: 'Library Registration Card',
    description: 'Scanned digital copy of the stamped institutional library card.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'req_lib_02',
    stageId: 'library',
    name: 'Library Clearance Evidence',
    description: 'Proof of no overdue book fines or lost items.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Faculty
  {
    id: 'req_fac_01',
    stageId: 'faculty',
    name: 'Departmental Dues Receipt',
    description: 'Departmental association registration fee payment slip.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'req_fac_02',
    stageId: 'faculty',
    name: 'Course Registration Form (Signed)',
    description: 'HOD signed and stamped final year semester course registration form.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Bursary
  {
    id: 'req_bur_01',
    stageId: 'bursary',
    name: 'School Fees Receipt (Final Session)',
    description: 'Official verified e-portal school fee payment receipt.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'req_bur_02',
    stageId: 'bursary',
    name: 'Bursary Clearance Evidence',
    description: 'Consolidated bursary audit teller and bank confirmation stamp.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Sports
  {
    id: 'req_spo_01',
    stageId: 'sports',
    name: 'Sports Levy & Equipment Clearance',
    description: 'Athletics board certificate confirming no pending sports gear returns.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Accommodation
  {
    id: 'req_acc_01',
    stageId: 'accommodation',
    name: 'Hostel Clearance Slip',
    description: 'Hall warden signed slip confirming room handover and no property damages.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Student Affairs
  {
    id: 'req_stu_01',
    stageId: 'student_affairs',
    name: 'Certificate of Good Conduct',
    description: 'Dean of Student Affairs moral certificate and non-cultism undertaking.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Graduation
  {
    id: 'req_gra_01',
    stageId: 'graduation',
    name: 'Convocation & Alumni Levy Receipt',
    description: 'Payment receipt for convocation brochure, gown, and alumni registration.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'req_gra_02',
    stageId: 'graduation',
    name: 'Final Project Defense Approval Form',
    description: 'Project supervisor and external examiner sign-off certificate.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
];

export const INITIAL_STAFF: StaffRecord[] = [
  {
    id: 'staff_super_admin',
    name: 'Prof. Adamu Garba',
    email: 'admin@clearpass.edu.ng',
    role: 'SUPER_ADMIN',
    departmentId: 'ICT_ADMIN',
    departmentName: 'Directorate of Academic Services',
    assignedStage: 'admission',
    active: true,
    createdAt: '2026-07-15T09:00:00Z',
    phone: '+234 803 111 2233',
  },
  {
    id: 'staff_bur_01',
    name: 'Hajiya Maryam Bello',
    email: 'bursary@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'BURSARY',
    departmentName: 'Bursary & Financial Services',
    assignedStage: 'bursary',
    active: true,
    createdAt: '2026-07-20T10:00:00Z',
    phone: '+234 802 334 4556',
  },
  {
    id: 'staff_lib_01',
    name: 'John Ibrahim',
    email: 'library@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'LIBRARY',
    departmentName: 'University Central Library',
    assignedStage: 'library',
    active: true,
    createdAt: '2026-07-20T11:00:00Z',
    phone: '+234 805 778 9900',
  },
  {
    id: 'staff_adm_01',
    name: 'Dr. Kabir Sadiq',
    email: 'admission@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'ACADEMIC_AFFAIRS',
    departmentName: 'Admissions Office',
    assignedStage: 'admission',
    active: true,
    createdAt: '2026-07-20T11:30:00Z',
    phone: '+234 809 223 3445',
  },
  {
    id: 'staff_fac_01',
    name: 'Dr. (Mrs) Ngozi Okoro',
    email: 'faculty@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'ENG_FACULTY',
    departmentName: 'Faculty of Engineering & Technology',
    assignedStage: 'faculty',
    active: true,
    createdAt: '2026-07-22T08:45:00Z',
    phone: '+234 806 445 5667',
  },
  {
    id: 'staff_spo_01',
    name: 'Coach Ahmed Usman',
    email: 'sports@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'SPORTS',
    departmentName: 'Directorate of Physical Education & Sports',
    assignedStage: 'sports',
    active: true,
    createdAt: '2026-07-25T14:15:00Z',
    phone: '+234 807 556 6778',
  },
  {
    id: 'staff_acc_01',
    name: 'Mrs. Amina Yusuf',
    email: 'accommodation@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'STUDENT_HOUSING',
    departmentName: 'Hostel Affairs & Accommodation',
    assignedStage: 'accommodation',
    active: true,
    createdAt: '2026-07-26T12:00:00Z',
    phone: '+234 813 667 7889',
  },
  {
    id: 'staff_stu_01',
    name: 'Barrister Tunde Adeleke',
    email: 'studentaffairs@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'STUDENT_AFFAIRS',
    departmentName: 'Division of Student Affairs',
    assignedStage: 'student_affairs',
    active: true,
    createdAt: '2026-07-27T09:30:00Z',
    phone: '+234 814 778 8990',
  },
  {
    id: 'staff_gra_01',
    name: 'Engr. Mustapha Umar',
    email: 'graduation@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'ACADEMIC_PLANNING',
    departmentName: 'Graduation & Records Division',
    assignedStage: 'graduation',
    active: true,
    createdAt: '2026-07-28T10:00:00Z',
    phone: '+234 818 889 9001',
  },
  {
    id: 'staff_admin_general',
    name: 'Dr. Faruk Abdullahi',
    email: 'coordinator@clearpass.edu.ng',
    role: 'ADMIN',
    departmentId: 'ACADEMIC_REGISTRY',
    departmentName: 'Academic Registry',
    assignedStage: 'admission',
    active: true,
    createdAt: '2026-07-18T10:00:00Z',
    phone: '+234 803 999 8877',
  },
];

export const INITIAL_STUDENTS: StudentRecord[] = [];

export const INITIAL_SUBMISSIONS: SubmissionRecord[] = [];

export const INITIAL_NOTIFICATIONS: NotificationRecord[] = [
  {
    id: 'notif_001',
    studentId: 'std_001',
    title: 'Submission Received',
    message: 'Your School Fees Receipt has been received for Bursary clearance review.',
    type: 'submission',
    read: true,
    createdAt: '2026-08-31T17:27:00Z',
  },
  {
    id: 'notif_002',
    studentId: 'std_004',
    title: 'Faculty Document Rejected',
    message: 'Your Departmental Dues Receipt was rejected: Missing information.',
    type: 'rejection',
    read: false,
    createdAt: '2026-08-30T11:30:00Z',
  },
  {
    id: 'notif_003',
    studentId: 'std_002',
    title: 'Clearance Fully Completed',
    message: 'Congratulations! All 8 clearance stages have been successfully approved.',
    type: 'approval',
    read: true,
    createdAt: '2026-08-29T15:45:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogRecord[] = [
  {
    id: 'audit_001',
    actorId: 'staff_fac_01',
    actorName: 'Dr. (Mrs) Ngozi Okoro',
    actorRole: 'STAFF',
    action: 'DOCUMENT_REJECTED',
    targetType: 'SUBMISSION',
    targetId: 'sub_007_fac_rej',
    metadata: {
      studentName: 'Fatima Danjuma',
      matricNumber: 'AC/24/088',
      stage: 'faculty',
      reason: 'Missing information',
    },
    createdAt: '2026-08-30T11:30:00Z',
  },
  {
    id: 'audit_002',
    actorId: 'staff_fac_01',
    actorName: 'Dr. (Mrs) Ngozi Okoro',
    actorRole: 'STAFF',
    action: 'DOCUMENT_APPROVED',
    targetType: 'SUBMISSION',
    targetId: 'sub_010_fac_app',
    metadata: {
      studentName: 'Muhammad Abubakar',
      matricNumber: 'CE/24/001',
      stage: 'faculty',
      requirement: 'Departmental Dues Receipt',
    },
    createdAt: '2026-08-22T09:15:00Z',
  },
  {
    id: 'audit_003',
    actorId: 'staff_lib_01',
    actorName: 'John Ibrahim',
    actorRole: 'STAFF',
    action: 'DOCUMENT_APPROVED',
    targetType: 'SUBMISSION',
    targetId: 'sub_009_lib_app',
    metadata: {
      studentName: 'Muhammad Abubakar',
      matricNumber: 'CE/24/001',
      stage: 'library',
      requirement: 'Library Registration Card',
    },
    createdAt: '2026-08-16T10:05:00Z',
  },
  {
    id: 'audit_004',
    actorId: 'staff_super_admin',
    actorName: 'Prof. Adamu Garba',
    actorRole: 'SUPER_ADMIN',
    action: 'STAFF_CREATED',
    targetType: 'STAFF',
    targetId: 'staff_bur_01',
    metadata: {
      assignedStage: 'bursary',
      email: 'bursary@clearpass.edu.ng',
    },
    createdAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'audit_005',
    actorId: 'staff_super_admin',
    actorName: 'Prof. Adamu Garba',
    actorRole: 'SUPER_ADMIN',
    action: 'SYSTEM_SETTINGS_UPDATED',
    targetType: 'SYSTEM',
    targetId: 'global',
    metadata: {
      institution: 'Jigawa State Polytechnic',
      session: '2025/2026',
    },
    createdAt: '2026-07-15T09:15:00Z',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  institutionName: 'Jigawa State Polytechnic',
  academicSession: '2025/2026',
  clearanceSystemStatus: 'ACTIVE',
  contactEmail: 'support@clearpass.jisp.edu.ng',
  superAdminEmail: 'admin@clearpass.edu.ng',
  lastUpdated: '2026-08-31T00:00:00Z',
};
