import {
  ClearanceStage,
  Requirement,
  StudentRecord,
  StaffRecord,
  SubmissionRecord,
  NotificationRecord,
  AuditLogRecord,
  SystemSettings,
  ClearanceStageKey,
} from '../types';

export const INITIAL_STAGES: ClearanceStage[] = [
  {
    id: 'admission',
    name: 'Admission',
    order: 1,
    active: true,
    description: 'Verification of JAMB Admission Letter, O-Level credentials, and registration records.',
    color: '#3B82F6',
  },
  {
    id: 'library',
    name: 'Library',
    order: 2,
    active: true,
    description: 'Library card validation and return of all borrowed books and electronic media.',
    color: '#8B5CF6',
  },
  {
    id: 'faculty',
    name: 'Faculty',
    order: 3,
    active: true,
    description: 'Departmental dues confirmation and academic course registration verification.',
    color: '#EC4899',
  },
  {
    id: 'bursary',
    name: 'Bursary',
    order: 4,
    active: true,
    description: 'Audit of school fees receipts, late payment clearance, and financial statement reconciliation.',
    color: '#F59E0B',
  },
  {
    id: 'sports',
    name: 'Sports',
    order: 5,
    active: true,
    description: 'Sports equipment return and athletics department clearance certificate.',
    color: '#10B981',
  },
  {
    id: 'accommodation',
    name: 'Accommodation',
    order: 6,
    active: true,
    description: 'Hostel residency validation, room damage assessment, and key handover confirmation.',
    color: '#6366F1',
  },
  {
    id: 'student_affairs',
    name: 'Student Affairs',
    order: 7,
    active: true,
    description: 'Certificate of good conduct, security clearance, and student association clearance.',
    color: '#06B6D4',
  },
  {
    id: 'graduation',
    name: 'Graduation',
    order: 8,
    active: true,
    description: 'Convocation fee receipt, alumni registration, and final project defense approval.',
    color: '#14B8A6',
  },
];

export const INITIAL_REQUIREMENTS: Requirement[] = [
  // Admission
  {
    id: 'req_adm_01',
    stageId: 'admission',
    name: 'JAMB Admission Letter',
    description: 'Official JAMB admission letter showing institutional verification.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'req_adm_02',
    stageId: 'admission',
    name: 'O-Level Certificate / Statement of Results',
    description: 'Original WAEC/NECO/NABTEB certificate or official statement of result.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Library
  {
    id: 'req_lib_01',
    stageId: 'library',
    name: 'Library Registration Card',
    description: 'Scanned digital copy of the stamped institutional library card.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'req_lib_02',
    stageId: 'library',
    name: 'Library Clearance Evidence',
    description: 'Proof of no overdue book fines or lost items.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Faculty
  {
    id: 'req_fac_01',
    stageId: 'faculty',
    name: 'Departmental Dues Receipt',
    description: 'Departmental association registration fee payment slip.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'req_fac_02',
    stageId: 'faculty',
    name: 'Course Registration Form (Signed)',
    description: 'HOD signed and stamped final year semester course registration form.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Bursary
  {
    id: 'req_bur_01',
    stageId: 'bursary',
    name: 'School Fees Receipt (Final Session)',
    description: 'Official verified e-portal school fee payment receipt.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'req_bur_02',
    stageId: 'bursary',
    name: 'Bursary Clearance Evidence',
    description: 'Consolidated bursary audit teller and bank confirmation stamp.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Sports
  {
    id: 'req_spo_01',
    stageId: 'sports',
    name: 'Sports Levy & Equipment Clearance',
    description: 'Athletics board certificate confirming no pending sports gear returns.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Accommodation
  {
    id: 'req_acc_01',
    stageId: 'accommodation',
    name: 'Hostel Clearance Slip',
    description: 'Hall warden signed slip confirming room handover and no property damages.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Student Affairs
  {
    id: 'req_stu_01',
    stageId: 'student_affairs',
    name: 'Certificate of Good Conduct',
    description: 'Dean of Student Affairs moral certificate and non-cultism undertaking.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  // Graduation
  {
    id: 'req_gra_01',
    stageId: 'graduation',
    name: 'Convocation & Alumni Levy Receipt',
    description: 'Payment receipt for convocation brochure, gown, and alumni registration.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'req_gra_02',
    stageId: 'graduation',
    name: 'Final Project Defense Approval Form',
    description: 'Project supervisor and external examiner sign-off certificate.',
    required: true,
    allowedFileTypes: ['pdf', 'jpg', 'png'],
    maxFileSize: 5,
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
];

export const INITIAL_STAFF: StaffRecord[] = [
  {
    id: 'staff_super_admin',
    name: 'Prof. Adamu Garba',
    email: 'admin@clearpass.edu.ng',
    role: 'SUPER_ADMIN',
    departmentId: 'ICT_ADMIN',
    departmentName: 'Directorate of Academic Services',
    assignedStage: 'admission',
    active: true,
    createdAt: '2026-07-15T09:00:00Z',
    phone: '+234 803 111 2233',
  },
  {
    id: 'staff_bur_01',
    name: 'Hajiya Maryam Bello',
    email: 'bursary@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'BURSARY',
    departmentName: 'Bursary & Financial Services',
    assignedStage: 'bursary',
    active: true,
    createdAt: '2026-07-20T10:00:00Z',
    phone: '+234 802 334 4556',
  },
  {
    id: 'staff_lib_01',
    name: 'John Ibrahim',
    email: 'library@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'LIBRARY',
    departmentName: 'University Central Library',
    assignedStage: 'library',
    active: true,
    createdAt: '2026-07-20T11:00:00Z',
    phone: '+234 805 778 9900',
  },
  {
    id: 'staff_adm_01',
    name: 'Dr. Kabir Sadiq',
    email: 'admission@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'ACADEMIC_AFFAIRS',
    departmentName: 'Admissions Office',
    assignedStage: 'admission',
    active: true,
    createdAt: '2026-07-20T11:30:00Z',
    phone: '+234 809 223 3445',
  },
  {
    id: 'staff_fac_01',
    name: 'Dr. (Mrs) Ngozi Okoro',
    email: 'faculty@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'ENG_FACULTY',
    departmentName: 'Faculty of Engineering & Technology',
    assignedStage: 'faculty',
    active: true,
    createdAt: '2026-07-22T08:45:00Z',
    phone: '+234 806 445 5667',
  },
  {
    id: 'staff_spo_01',
    name: 'Coach Ahmed Usman',
    email: 'sports@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'SPORTS',
    departmentName: 'Directorate of Physical Education & Sports',
    assignedStage: 'sports',
    active: true,
    createdAt: '2026-07-25T14:15:00Z',
    phone: '+234 807 556 6778',
  },
  {
    id: 'staff_acc_01',
    name: 'Mrs. Amina Yusuf',
    email: 'accommodation@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'STUDENT_HOUSING',
    departmentName: 'Hostel Affairs & Accommodation',
    assignedStage: 'accommodation',
    active: true,
    createdAt: '2026-07-26T12:00:00Z',
    phone: '+234 813 667 7889',
  },
  {
    id: 'staff_stu_01',
    name: 'Barrister Tunde Adeleke',
    email: 'studentaffairs@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'STUDENT_AFFAIRS',
    departmentName: 'Division of Student Affairs',
    assignedStage: 'student_affairs',
    active: true,
    createdAt: '2026-07-27T09:30:00Z',
    phone: '+234 814 778 8990',
  },
  {
    id: 'staff_gra_01',
    name: 'Engr. Mustapha Umar',
    email: 'graduation@clearpass.edu.ng',
    role: 'STAFF',
    departmentId: 'ACADEMIC_PLANNING',
    departmentName: 'Graduation & Records Division',
    assignedStage: 'graduation',
    active: true,
    createdAt: '2026-07-28T10:00:00Z',
    phone: '+234 818 889 9001',
  },
  {
    id: 'staff_admin_general',
    name: 'Dr. Faruk Abdullahi',
    email: 'coordinator@clearpass.edu.ng',
    role: 'ADMIN',
    departmentId: 'ACADEMIC_REGISTRY',
    departmentName: 'Academic Registry',
    assignedStage: 'admission',
    active: true,
    createdAt: '2026-07-18T10:00:00Z',
    phone: '+234 803 999 8877',
  },
];

export const INITIAL_STUDENTS: StudentRecord[] = [
  {
    id: 'std_001',
    name: 'Muhammad Abubakar',
    matricNumber: 'CE/24/001',
    email: 'm.abubakar@student.jisp.edu.ng',
    departmentId: 'COMP_ENG',
    departmentName: 'Computer Engineering',
    level: 'HND II',
    session: '2025/2026',
    clearanceStatus: 'in_progress',
    currentStage: 'bursary',
    progressPercent: 37.5,
    stagesStatus: {
      admission: 'approved',
      library: 'approved',
      faculty: 'approved',
      bursary: 'pending',
      sports: 'not_started',
      accommodation: 'not_started',
      student_affairs: 'not_started',
      graduation: 'not_started',
    },
    active: true,
    createdAt: '2026-08-10T11:00:00Z',
    phoneNumber: '+234 812 345 6789',
  },
  {
    id: 'std_002',
    name: 'Aisha Ibrahim',
    matricNumber: 'CS/24/042',
    email: 'aisha.ibrahim@student.jisp.edu.ng',
    departmentId: 'COMP_SCI',
    departmentName: 'Computer Science',
    level: 'HND II',
    session: '2025/2026',
    clearanceStatus: 'completed',
    currentStage: 'graduation',
    progressPercent: 100,
    stagesStatus: {
      admission: 'approved',
      library: 'approved',
      faculty: 'approved',
      bursary: 'approved',
      sports: 'approved',
      accommodation: 'approved',
      student_affairs: 'approved',
      graduation: 'approved',
    },
    active: true,
    createdAt: '2026-08-05T09:30:00Z',
    phoneNumber: '+234 803 456 7890',
  },
  {
    id: 'std_003',
    name: 'Emmanuel Okon',
    matricNumber: 'EE/24/019',
    email: 'e.okon@student.jisp.edu.ng',
    departmentId: 'ELECT_ENG',
    departmentName: 'Electrical Engineering',
    level: 'ND II',
    session: '2025/2026',
    clearanceStatus: 'in_progress',
    currentStage: 'library',
    progressPercent: 12.5,
    stagesStatus: {
      admission: 'approved',
      library: 'pending',
      faculty: 'not_started',
      bursary: 'not_started',
      sports: 'not_started',
      accommodation: 'not_started',
      student_affairs: 'not_started',
      graduation: 'not_started',
    },
    active: true,
    createdAt: '2026-08-12T14:20:00Z',
    phoneNumber: '+234 809 112 2334',
  },
  {
    id: 'std_004',
    name: 'Fatima Danjuma',
    matricNumber: 'AC/24/088',
    email: 'f.danjuma@student.jisp.edu.ng',
    departmentId: 'ACCOUNTANCY',
    departmentName: 'Accountancy',
    level: 'HND II',
    session: '2025/2026',
    clearanceStatus: 'in_progress',
    currentStage: 'faculty',
    progressPercent: 25,
    stagesStatus: {
      admission: 'approved',
      library: 'approved',
      faculty: 'rejected',
      bursary: 'not_started',
      sports: 'not_started',
      accommodation: 'not_started',
      student_affairs: 'not_started',
      graduation: 'not_started',
    },
    active: true,
    createdAt: '2026-08-14T10:15:00Z',
    phoneNumber: '+234 814 556 7788',
  },
  {
    id: 'std_005',
    name: 'Chidi Nwankwo',
    matricNumber: 'SLT/24/112',
    email: 'chidi.n@student.jisp.edu.ng',
    departmentId: 'SCIENCE_LAB',
    departmentName: 'Science Laboratory Technology',
    level: 'HND II',
    session: '2025/2026',
    clearanceStatus: 'in_progress',
    currentStage: 'sports',
    progressPercent: 50,
    stagesStatus: {
      admission: 'approved',
      library: 'approved',
      faculty: 'approved',
      bursary: 'approved',
      sports: 'pending',
      accommodation: 'not_started',
      student_affairs: 'not_started',
      graduation: 'not_started',
    },
    active: true,
    createdAt: '2026-08-15T16:00:00Z',
    phoneNumber: '+234 816 778 9900',
  },
  {
    id: 'std_006',
    name: 'Blessing Eze',
    matricNumber: 'ME/24/055',
    email: 'b.eze@student.jisp.edu.ng',
    departmentId: 'MECH_ENG',
    departmentName: 'Mechanical Engineering',
    level: 'HND II',
    session: '2025/2026',
    clearanceStatus: 'in_progress',
    currentStage: 'accommodation',
    progressPercent: 62.5,
    stagesStatus: {
      admission: 'approved',
      library: 'approved',
      faculty: 'approved',
      bursary: 'approved',
      sports: 'approved',
      accommodation: 'pending',
      student_affairs: 'not_started',
      graduation: 'not_started',
    },
    active: true,
    createdAt: '2026-08-16T08:30:00Z',
    phoneNumber: '+234 802 331 4455',
  },
  {
    id: 'std_007',
    name: 'Yakubu Musa',
    matricNumber: 'CE/24/023',
    email: 'yakubu.m@student.jisp.edu.ng',
    departmentId: 'COMP_ENG',
    departmentName: 'Computer Engineering',
    level: 'HND II',
    session: '2025/2026',
    clearanceStatus: 'in_progress',
    currentStage: 'student_affairs',
    progressPercent: 75,
    stagesStatus: {
      admission: 'approved',
      library: 'approved',
      faculty: 'approved',
      bursary: 'approved',
      sports: 'approved',
      accommodation: 'approved',
      student_affairs: 'pending',
      graduation: 'not_started',
    },
    active: true,
    createdAt: '2026-08-18T13:45:00Z',
    phoneNumber: '+234 808 990 1122',
  },
  {
    id: 'std_008',
    name: 'Zainab Sani',
    matricNumber: 'CS/24/071',
    email: 'zainab.sani@student.jisp.edu.ng',
    departmentId: 'COMP_SCI',
    departmentName: 'Computer Science',
    level: 'HND II',
    session: '2025/2026',
    clearanceStatus: 'in_progress',
    currentStage: 'graduation',
    progressPercent: 87.5,
    stagesStatus: {
      admission: 'approved',
      library: 'approved',
      faculty: 'approved',
      bursary: 'approved',
      sports: 'approved',
      accommodation: 'approved',
      student_affairs: 'approved',
      graduation: 'pending',
    },
    active: true,
    createdAt: '2026-08-20T11:10:00Z',
    phoneNumber: '+234 811 223 4455',
  },
];

export const INITIAL_SUBMISSIONS: SubmissionRecord[] = [
  // 1. Muhammad Abubakar - Bursary Pending (Key test item from prompt!)
  {
    id: 'sub_001_bur',
    studentId: 'std_001',
    studentName: 'Muhammad Abubakar',
    matricNumber: 'CE/24/001',
    departmentName: 'Computer Engineering',
    requirementId: 'req_bur_01',
    requirementName: 'School Fees Receipt (Final Session)',
    stageId: 'bursary',
    stageName: 'Bursary',
    fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1200&q=80',
    fileName: 'School_Fees_Receipt_CE24001.pdf',
    fileType: 'pdf',
    fileSize: 1420000,
    status: 'pending',
    submittedAt: '2026-08-31T17:27:00Z',
  },
  // 2. Emmanuel Okon - Library Pending
  {
    id: 'sub_002_lib',
    studentId: 'std_003',
    studentName: 'Emmanuel Okon',
    matricNumber: 'EE/24/019',
    departmentName: 'Electrical Engineering',
    requirementId: 'req_lib_01',
    requirementName: 'Library Registration Card',
    stageId: 'library',
    stageName: 'Library',
    fileUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=1200&q=80',
    fileName: 'Library_Card_Scanned_EE019.jpg',
    fileType: 'jpg',
    fileSize: 890000,
    status: 'pending',
    submittedAt: '2026-08-31T15:10:00Z',
  },
  // 3. Chidi Nwankwo - Sports Pending
  {
    id: 'sub_003_spo',
    studentId: 'std_005',
    studentName: 'Chidi Nwankwo',
    matricNumber: 'SLT/24/112',
    departmentName: 'Science Laboratory Technology',
    requirementId: 'req_spo_01',
    requirementName: 'Sports Levy & Equipment Clearance',
    stageId: 'sports',
    stageName: 'Sports',
    fileUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1200&q=80',
    fileName: 'Sports_Levy_Slip_SLT112.pdf',
    fileType: 'pdf',
    fileSize: 1100000,
    status: 'pending',
    submittedAt: '2026-08-31T14:40:00Z',
  },
  // 4. Blessing Eze - Accommodation Pending
  {
    id: 'sub_004_acc',
    studentId: 'std_006',
    studentName: 'Blessing Eze',
    matricNumber: 'ME/24/055',
    departmentName: 'Mechanical Engineering',
    requirementId: 'req_acc_01',
    requirementName: 'Hostel Clearance Slip',
    stageId: 'accommodation',
    stageName: 'Accommodation',
    fileUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    fileName: 'Hostel_Handover_Form_ME055.png',
    fileType: 'png',
    fileSize: 1750000,
    status: 'pending',
    submittedAt: '2026-08-31T12:15:00Z',
  },
  // 5. Yakubu Musa - Student Affairs Pending
  {
    id: 'sub_005_stu',
    studentId: 'std_007',
    studentName: 'Yakubu Musa',
    matricNumber: 'CE/24/023',
    departmentName: 'Computer Engineering',
    requirementId: 'req_stu_01',
    requirementName: 'Certificate of Good Conduct',
    stageId: 'student_affairs',
    stageName: 'Student Affairs',
    fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80',
    fileName: 'Good_Conduct_Cert_CE023.pdf',
    fileType: 'pdf',
    fileSize: 2100000,
    status: 'pending',
    submittedAt: '2026-08-31T09:20:00Z',
  },
  // 6. Zainab Sani - Graduation Pending
  {
    id: 'sub_006_gra',
    studentId: 'std_008',
    studentName: 'Zainab Sani',
    matricNumber: 'CS/24/071',
    departmentName: 'Computer Science',
    requirementId: 'req_gra_01',
    requirementName: 'Convocation & Alumni Levy Receipt',
    stageId: 'graduation',
    stageName: 'Graduation',
    fileUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80',
    fileName: 'Convocation_Receipt_CS071.pdf',
    fileType: 'pdf',
    fileSize: 950000,
    status: 'pending',
    submittedAt: '2026-08-30T16:50:00Z',
  },
  // 7. Fatima Danjuma - Faculty REJECTED
  {
    id: 'sub_007_fac_rej',
    studentId: 'std_004',
    studentName: 'Fatima Danjuma',
    matricNumber: 'AC/24/088',
    departmentName: 'Accountancy',
    requirementId: 'req_fac_01',
    requirementName: 'Departmental Dues Receipt',
    stageId: 'faculty',
    stageName: 'Faculty',
    fileUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=1200&q=80',
    fileName: 'Dept_Dues_Slip_AC088.jpg',
    fileType: 'jpg',
    fileSize: 620000,
    status: 'rejected',
    submittedAt: '2026-08-29T10:00:00Z',
    reviewedAt: '2026-08-30T11:30:00Z',
    reviewedBy: 'staff_fac_01',
    reviewerName: 'Dr. (Mrs) Ngozi Okoro',
    rejectionReason: 'Missing information',
    reviewComment: 'Receipt is missing official departmental treasurer stamp and session indicator.',
  },
  // 8. Muhammad Abubakar - Admission APPROVED
  {
    id: 'sub_008_adm_app',
    studentId: 'std_001',
    studentName: 'Muhammad Abubakar',
    matricNumber: 'CE/24/001',
    departmentName: 'Computer Engineering',
    requirementId: 'req_adm_01',
    requirementName: 'JAMB Admission Letter',
    stageId: 'admission',
    stageName: 'Admission',
    fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80',
    fileName: 'JAMB_Letter_Verified_CE001.pdf',
    fileType: 'pdf',
    fileSize: 1340000,
    status: 'approved',
    submittedAt: '2026-08-11T09:00:00Z',
    reviewedAt: '2026-08-12T14:10:00Z',
    reviewedBy: 'staff_adm_01',
    reviewerName: 'Dr. Kabir Sadiq',
    reviewComment: 'Verified against JAMB CAPS Central Database.',
  },
  // 9. Muhammad Abubakar - Library APPROVED
  {
    id: 'sub_009_lib_app',
    studentId: 'std_001',
    studentName: 'Muhammad Abubakar',
    matricNumber: 'CE/24/001',
    departmentName: 'Computer Engineering',
    requirementId: 'req_lib_01',
    requirementName: 'Library Registration Card',
    stageId: 'library',
    stageName: 'Library',
    fileUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=1200&q=80',
    fileName: 'Library_Card_CE001.jpg',
    fileType: 'jpg',
    fileSize: 780000,
    status: 'approved',
    submittedAt: '2026-08-15T11:20:00Z',
    reviewedAt: '2026-08-16T10:05:00Z',
    reviewedBy: 'staff_lib_01',
    reviewerName: 'John Ibrahim',
    reviewComment: 'No outstanding catalog items or unreturned books.',
  },
  // 10. Muhammad Abubakar - Faculty APPROVED
  {
    id: 'sub_010_fac_app',
    studentId: 'std_001',
    studentName: 'Muhammad Abubakar',
    matricNumber: 'CE/24/001',
    departmentName: 'Computer Engineering',
    requirementId: 'req_fac_01',
    requirementName: 'Departmental Dues Receipt',
    stageId: 'faculty',
    stageName: 'Faculty',
    fileUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=1200&q=80',
    fileName: 'Faculty_Dues_CE001.pdf',
    fileType: 'pdf',
    fileSize: 920000,
    status: 'approved',
    submittedAt: '2026-08-20T14:30:00Z',
    reviewedAt: '2026-08-22T09:15:00Z',
    reviewedBy: 'staff_fac_01',
    reviewerName: 'Dr. (Mrs) Ngozi Okoro',
    reviewComment: 'Departmental clearance endorsed by HOD.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationRecord[] = [
  {
    id: 'notif_001',
    studentId: 'std_001',
    title: 'Submission Received',
    message: 'Your School Fees Receipt has been received for Bursary clearance review.',
    type: 'submission',
    read: true,
    createdAt: '2026-08-31T17:27:00Z',
  },
  {
    id: 'notif_002',
    studentId: 'std_004',
    title: 'Faculty Document Rejected',
    message: 'Your Departmental Dues Receipt was rejected: Missing information.',
    type: 'rejection',
    read: false,
    createdAt: '2026-08-30T11:30:00Z',
  },
  {
    id: 'notif_003',
    studentId: 'std_002',
    title: 'Clearance Fully Completed',
    message: 'Congratulations! All 8 clearance stages have been successfully approved.',
    type: 'approval',
    read: true,
    createdAt: '2026-08-29T15:45:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogRecord[] = [
  {
    id: 'audit_001',
    actorId: 'staff_fac_01',
    actorName: 'Dr. (Mrs) Ngozi Okoro',
    actorRole: 'STAFF',
    action: 'DOCUMENT_REJECTED',
    targetType: 'SUBMISSION',
    targetId: 'sub_007_fac_rej',
    metadata: {
      studentName: 'Fatima Danjuma',
      matricNumber: 'AC/24/088',
      stage: 'faculty',
      reason: 'Missing information',
    },
    createdAt: '2026-08-30T11:30:00Z',
  },
  {
    id: 'audit_002',
    actorId: 'staff_fac_01',
    actorName: 'Dr. (Mrs) Ngozi Okoro',
    actorRole: 'STAFF',
    action: 'DOCUMENT_APPROVED',
    targetType: 'SUBMISSION',
    targetId: 'sub_010_fac_app',
    metadata: {
      studentName: 'Muhammad Abubakar',
      matricNumber: 'CE/24/001',
      stage: 'faculty',
      requirement: 'Departmental Dues Receipt',
    },
    createdAt: '2026-08-22T09:15:00Z',
  },
  {
    id: 'audit_003',
    actorId: 'staff_lib_01',
    actorName: 'John Ibrahim',
    actorRole: 'STAFF',
    action: 'DOCUMENT_APPROVED',
    targetType: 'SUBMISSION',
    targetId: 'sub_009_lib_app',
    metadata: {
      studentName: 'Muhammad Abubakar',
      matricNumber: 'CE/24/001',
      stage: 'library',
      requirement: 'Library Registration Card',
    },
    createdAt: '2026-08-16T10:05:00Z',
  },
  {
    id: 'audit_004',
    actorId: 'staff_super_admin',
    actorName: 'Prof. Adamu Garba',
    actorRole: 'SUPER_ADMIN',
    action: 'STAFF_CREATED',
    targetType: 'STAFF',
    targetId: 'staff_bur_01',
    metadata: {
      assignedStage: 'bursary',
      email: 'bursary@clearpass.edu.ng',
    },
    createdAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'audit_005',
    actorId: 'staff_super_admin',
    actorName: 'Prof. Adamu Garba',
    actorRole: 'SUPER_ADMIN',
    action: 'SYSTEM_SETTINGS_UPDATED',
    targetType: 'SYSTEM',
    targetId: 'global',
    metadata: {
      institution: 'Jigawa State Polytechnic',
      session: '2025/2026',
    },
    createdAt: '2026-07-15T09:15:00Z',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  institutionName: 'Jigawa State Polytechnic',
  academicSession: '2025/2026',
  clearanceSystemStatus: 'ACTIVE',
  contactEmail: 'support@clearpass.jisp.edu.ng',
  superAdminEmail: 'admin@clearpass.edu.ng',
  lastUpdated: '2026-08-31T00:00:00Z',
};
